### ISSUE TITLE
Use one "upload" field and select style with dropdown/radio buttons

### ISSUE THREAD

**Issue by Bazzagibbs** [J5kinner/40ksheets-ReactJS-Firebase#6]
![image](https://user-images.githubusercontent.com/20216946/157598241-4c79cf39-aa06-4586-ac7a-7c03dba343ed.png)

**Comment by J5kinner** [comment]
I deviated a little bit on the design but I've finished the main idea ⭐️
LMK what you think @Bazzagibbs

**Comment by Bazzagibbs** [comment]
Very clean! Much better than my mock up haha
